--- 
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [biblio.bib]
biblio-style: apalike
link-citations: yes
---

# LIMNOLOGIA CON R {-}

Taller dictado en el marco del **IV Congreso Iberoamericano de Limnología - X Congreso Argentino de Limnología (IV CIL – CAL X)**, 27 y 28 de julio de 2023 .

El material se elaboró utilizando el paquete _bookdown_ [@R-bookdown; @bookdown2016], basado en _R Markdown_ [@rmarkdown2020] y _knitr_ [@xie2015].

**Docentes**: Natalia Morandeira, María E. Llames, Sofía Caruso, Patricia E.García, Joaquín Cochero, Julieta Capeletti y María Victoria Quiroga.

**Coordinadora**: María Victoria Quiroga.

## Contenido

**Unidad** \@ref(intro): Introducción a R y RStudio. Importación y manejo de datos en R. Gráficos exploratorios básicos.

**Unidad** \@ref(regmul): Correlación, regresión múltiple.

**Unidad** \@ref(gam): Modelos Aditivos Generalizados.

**Unidad** \@ref(multi1): Análisis multivariados I. PCA, NMDS, PERMANOVA.

**Unidad** \@ref(multi2): Análisis multivariados II. DCA, RDA, dbRDA.

**Unidad** \@ref(metrix): Paquete _metrix_. Estimar métricas (individuales y ecológicas) e índices bióticos basados en macroinvertebrados acuáticos para evaluar la calidad del agua.

**Unidad** \@ref(diathor): Paquete _DiaThor_. Estimación de información ecológica e índices bióticos para diatomeas. Paquete _optimos.prime_. Estimación de óptimo y rango de tolerancia de una especie.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
